obj-$(CONFIG_QPNP_FG_GEN4)	+= qpnp-fg-gen4.o fg-util.o fg-memif.o fg-alg.o pmic-voter.o of_batterydata.o
#obj-$(CONFIG_QPNP_SMB5_NABU)	+= qpnp-smb5-nabu.o smb5-lib-nabu.o pmic-voter.o
obj-$(CONFIG_QPNP_SMB5_NABU)	+= pm8150b_charger.o smb5-lib.o
obj-$(CONFIG_QPNP_SMB5_NABU)	+= usbpd_manager.o
